version: '3.0'

services:
  pinot:
    container_name: 'pinot'
    image: apachepinot/pinot:latest
    ports:
      - 9000:9000/tcp
      - 8000:8000/tcp
      - 2123:2123/tcp
    command:
      - QuickStart
      - -type
      - batch
  grafana:
    container_name: 'startree-pinot-datasource'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-9.5.3}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/startree-pinot-datasource
      - ./provisioning:/etc/grafana/provisioning
