services:
  pinot:
    container_name: 'pinot'
    image: 'repo.startreedata.io/startree-docker-registry/startree-pinot:2.12.27'
    ports:
      - '9000:9000/tcp' # Controller
      - '8000:8000/tcp' # Broker
      - '2123:2123/tcp' # Zookeeper
      - '7050:7050/tcp' # Server
      - '6000:6000/tcp' # Minion
      - '8097:8097/tcp'
    command:
      - 'StarTreeQuickStart'
      - '-type'
      - 'PROMQL_TIME_SERIES'

  oss-pinot:
    container_name: 'oss-pinot'
    image: 'apachepinot/pinot:latest'
    ports:
      - '9000:9000/tcp' # Controller
      - '8000:8000/tcp' # Broker
      - '2123:2123/tcp' # Zookeeper
      - '7050:7050/tcp' # Server
      - '6000:6000/tcp' # Minion
      - '8097:8097/tcp'
    command:
      - 'QuickStart'
      - '-type'
      - 'batch'

  grafana:
    healthcheck:
      test: ['CMD', '/usr/bin/wget', '-O', '/dev/null', 'http://localhost:3000']
      interval: 5s
      timeout: 120s
      retries: 50

    platform: 'linux/amd64'
    build:
      args:
        grafana_version: ${GRAFANA_VERSION:-9.1.1}
    ports:
      - 3000:3000/tcp
    volumes:
      - grafana_data:/var/lib/grafana

    environment:
      GF_SERVER_ROOT_URL: http://localhost:3000
      GF_AUTH_GENERIC_OAUTH_ENABLED: true
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://identity.metrics.analytics.startree.cloud/auth
      GF_AUTH_GENERIC_OAUTH_API_URL: https://identity.metrics.analytics.startree.cloud/userinfo
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://identity.metrics.analytics.startree.cloud/token
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: pinot-grafana-demo
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: OizfKsWuucCdXB65CR3XDbOZ
      GF_AUTH_GENERIC_OAUTH_SCOPES: openid profile email groups
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: true || 'Admin'
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana

volumes:
  grafana_data:
