services:
  pinot:
    container_name: 'pinot'
    image: 'repo.startreedata.io/startree-docker-registry/startree-pinot:timeseries-promql-nov-6'
    ports:
      - '9000:9000/tcp' # Controller
      - '8000:8000/tcp' # Broker
      - '2123:2123/tcp' # Zookeeper
      - '7050:7050/tcp' # Server
      - '6000:6000/tcp' # Minion
      - '8097:8097/tcp'
    command:
      - 'StarTreeQuickStart'
      - '-type'
      - 'PROMQL_TIME_SERIES'

  grafana:
    user: root
    container_name: 'startree-pinot-datasource'

    healthcheck:
      test: ['CMD', '/usr/bin/wget', '-O', '/dev/null', 'http://localhost:3000']
      interval: 5s
      timeout: 120s
      retries: 50

    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-9.1.1}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - grafana_data:/var/lib/grafana
      - ./dist:/var/lib/grafana/plugins/startree-pinot-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/startree-pinot-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.startree-pinot-datasource:debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: startree-pinot-datasource

volumes:
  grafana_data:
