services:
  pinot:
    container_name: 'pinot'
    image: apachepinot/pinot:latest
    ports:
      - 9000:9000/tcp
      - 8000:8000/tcp
      - 2123:2123/tcp
    command:
      - QuickStart
      - -type
      - batch

    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:9000/tables | grep billing"]
      interval: 5s
      timeout: 10s
      retries: 50
      start_period: 60

  grafana:
    user: root
    container_name: 'startree-pinot-datasource'

    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.4.2}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/startree-pinot-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/startree-pinot-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.startree-pinot-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: startree-pinot-datasource
