apiVersion: v1
kind: Service
metadata:
  name: metrics-partitioner
  namespace: cell-u5gvpr-default
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: metrics-partitioner
