name: Create Customer Release

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: A single word description for this release, e.g. graphiant.
        required: true
      root_urls:
        description: Comma-separated root urls of the intended Grafana instance, e.g. https://grafana.envId.orgId.startree.cloud.
        required: true

run-name: Publish release for ${{ inputs.release_name }} triggered by @${{ github.actor }}

jobs:
  build:
    name: Create Customer Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Sign release
        run: go run cmd/release/main.go resign ${{ inputs.root_urls }}
        env:
          GRAFANA_ACCESS_POLICY_TOKEN: ${{ secrets.GRAFANA_ACCESS_POLICY_TOKEN }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
          RELEASE_NAME: ${{ inputs.release_name }}
