name: Latest Grafana API compatibility check
on: [pull_request]

jobs:
  compatibilitycheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Build plugin
        run: npm run build
      - name: Find module.ts or module.tsx
        id: find-module-ts
        run: >-
          MODULETS="$(find ./src -type f \( -name "module.ts" -o -name
          "module.tsx" \))"

          echo "modulets=${MODULETS}" >> $GITHUB_OUTPUT
      - name: Compatibility check
        uses: grafana/plugin-actions/is-compatible@main
        with:
          module: ${{ steps.find-module-ts.outputs.modulets }}
          comment-pr: no
          fail-if-incompatible: yes
