# This GitHub Action automates the process of building Grafana plugins.
# (For more information, see https://github.com/grafana/plugin-actions/blob/main/build-plugin/README.md)
name: Release

on:
  workflow_dispatch:
    inputs:
      newVersion:
        type: choice
        description: New version is
        options:
          - patch
          - minor
          - major

permissions: read-all

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install node dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Login in Docker registry
        uses: docker/login-action@v3
        with:
          registry: repo.startreedata.io/startree-docker-registry
          username: ${{ secrets.MVN_REPOSITORY_USERNAME }}
          password: ${{ secrets.MVN_REPOSITORY_PASSWORD }}

      - name: Bump the release version
        id: version
        run: |
          git config --global user.email "ci@startree.ai"
          git config --global user.name "CI"
          version=$(npm version ${{ github.event.inputs.newVersion }})
          #git push --follow-tags
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Build & upload the release
        run: go run cmd/release/main.go create
        env:
          GRAFANA_ACCESS_POLICY_TOKEN: ${{ secrets.GRAFANA_ACCESS_POLICY_TOKEN }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}

      - name: Publish startree-grafana image
        uses: docker/build-push-action@v6
        with:
          file: startree-cloud/Dockerfile
          context: .
          push: true
          tags: |
            repo.startreedata.io/startree-docker-registry/startree-grafana:${{ steps.version.outputs.version }}
            repo.startreedata.io/startree-docker-registry/startree-grafana:latest

      - name: Set prerelease version
        run: |
          npm version --no-git-tag-version prerelease --preid pre
          git add package.json
          git commit -m'prepare for next version'
          #git push --follow-tags
        env:
          VERSION: ${{ steps.version.outputs.version }}
